dist: bionic
sudo: required

language: python
python:
  - "3.8"

install:
  - pip install ansible-lint
script:
  - if ansible-lint -R -r ./rules tests/positive/*.yml; then echo "Positive tests OK"; (exit 0); else if [ $? -eq 2 ]; then echo "Positive tests is failed"; (exit 1); else echo "You rules is broken"; (exit 1); fi; fi
  - if ansible-lint -R -r ./rules tests/negative/*.yml; then echo "Negative tests failed"; (exit 1); else if [ $? -eq 2 ]; then echo "Negative tests OK"; (exit 0); else echo "You rules is broken"; (exit 1); fi; fi
